# Generated by Django 5.2.1 on 2025-06-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tip'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='career_advice_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Tip',
        ),
    ]
